<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory;

class PermissionsSeeder extends Seeder
{

    /**
     * Run the database seeder and seed Roles and permissions entries.
     *
     * @return void
     */
    public function run()
    {
        DB::table('roles')->insert([
				['id' => 1, 'name' => 'SuperAdmin', 'guard_name' => 'admin'],
				['id' => 2, 'name' => 'Manager', 'guard_name' => 'admin'],
				['id' => 3, 'name' => 'Editor', 'guard_name' => 'admin'],
				['id' => 4, 'name' => 'Viewer', 'guard_name' => 'admin']
			]);

        DB::table('permissions')->insert([
				['id' => 1, 'name' => 'list users', 'guard_name' => 'admin'],
				['id' => 2, 'name' => 'view users', 'guard_name' => 'admin'],
				['id' => 3, 'name' => 'add users', 'guard_name' => 'admin'],
				['id' => 4, 'name' => 'edit users', 'guard_name' => 'admin'],
				['id' => 5, 'name' => 'delete users', 'guard_name' => 'admin'],
				['id' => 6, 'name' => 'restore users', 'guard_name' => 'admin'],
				['id' => 7, 'name' => 'erease users', 'guard_name' => 'admin'],
				['id' => 8, 'name' => 'list products', 'guard_name' => 'admin'],
				['id' => 9, 'name' => 'view products', 'guard_name' => 'admin'],
				['id' => 10, 'name' => 'add products', 'guard_name' => 'admin'],
				['id' => 11, 'name' => 'edit products', 'guard_name' => 'admin'],
				['id' => 12, 'name' => 'delete products', 'guard_name' => 'admin'],
				['id' => 13, 'name' => 'restore products', 'guard_name' => 'admin'],
				['id' => 14, 'name' => 'erease products', 'guard_name' => 'admin'],
				['id' => 15, 'name' => 'list categories', 'guard_name' => 'admin'],
				['id' => 16, 'name' => 'view categories', 'guard_name' => 'admin'],
				['id' => 17, 'name' => 'add categories', 'guard_name' => 'admin'],
				['id' => 18, 'name' => 'edit categories', 'guard_name' => 'admin'],
				['id' => 19, 'name' => 'delete categories', 'guard_name' => 'admin'],
				['id' => 20, 'name' => 'restore categories', 'guard_name' => 'admin'],
				['id' => 21, 'name' => 'erease categories', 'guard_name' => 'admin'],
				['id' => 22, 'name' => 'list tags', 'guard_name' => 'admin'],
				['id' => 23, 'name' => 'view tags', 'guard_name' => 'admin'],
				['id' => 24, 'name' => 'add tags', 'guard_name' => 'admin'],
				['id' => 25, 'name' => 'edit tags', 'guard_name' => 'admin'],
				['id' => 26, 'name' => 'delete tags', 'guard_name' => 'admin'],
				['id' => 27, 'name' => 'restore tags', 'guard_name' => 'admin'],
				['id' => 28, 'name' => 'erease tags', 'guard_name' => 'admin'],
				['id' => 29, 'name' => 'list images', 'guard_name' => 'admin'],
				['id' => 30, 'name' => 'view images', 'guard_name' => 'admin'],
				['id' => 31, 'name' => 'add images', 'guard_name' => 'admin'],
				['id' => 32, 'name' => 'edit images', 'guard_name' => 'admin'],
				['id' => 33, 'name' => 'delete images', 'guard_name' => 'admin'],
				['id' => 34, 'name' => 'restore images', 'guard_name' => 'admin'],
				['id' => 35, 'name' => 'erease images', 'guard_name' => 'admin'],
				['id' => 36, 'name' => 'list variants', 'guard_name' => 'admin'],
				['id' => 37, 'name' => 'view variants', 'guard_name' => 'admin'],
				['id' => 38, 'name' => 'add variants', 'guard_name' => 'admin'],
				['id' => 39, 'name' => 'edit variants', 'guard_name' => 'admin'],
				['id' => 40, 'name' => 'delete variants', 'guard_name' => 'admin'],
				['id' => 41, 'name' => 'restore variants', 'guard_name' => 'admin'],
				['id' => 42, 'name' => 'erease variants', 'guard_name' => 'admin'],
				['id' => 43, 'name' => 'list carts', 'guard_name' => 'admin'],
				['id' => 44, 'name' => 'view carts', 'guard_name' => 'admin'],
				['id' => 45, 'name' => 'add carts', 'guard_name' => 'admin'],
				['id' => 46, 'name' => 'edit carts', 'guard_name' => 'admin'],
				['id' => 47, 'name' => 'delete carts', 'guard_name' => 'admin'],
				['id' => 48, 'name' => 'list cart_items', 'guard_name' => 'admin'],
				['id' => 49, 'name' => 'view cart_items', 'guard_name' => 'admin'],
				['id' => 50, 'name' => 'add cart_items', 'guard_name' => 'admin'],
				['id' => 51, 'name' => 'edit cart_items', 'guard_name' => 'admin'],
				['id' => 52, 'name' => 'delete cart_items', 'guard_name' => 'admin'],
				['id' => 53, 'name' => 'list orders', 'guard_name' => 'admin'],
				['id' => 54, 'name' => 'view orders', 'guard_name' => 'admin'],
				['id' => 55, 'name' => 'add orders', 'guard_name' => 'admin'],
				['id' => 56, 'name' => 'edit orders', 'guard_name' => 'admin'],
				['id' => 57, 'name' => 'delete orders', 'guard_name' => 'admin'],
				['id' => 58, 'name' => 'restore orders', 'guard_name' => 'admin'],
				['id' => 59, 'name' => 'erease orders', 'guard_name' => 'admin'],
				['id' => 60, 'name' => 'list order_items', 'guard_name' => 'admin'],
				['id' => 61, 'name' => 'view order_items', 'guard_name' => 'admin'],
				['id' => 62, 'name' => 'add order_items', 'guard_name' => 'admin'],
				['id' => 63, 'name' => 'edit order_items', 'guard_name' => 'admin'],
				['id' => 64, 'name' => 'delete order_items', 'guard_name' => 'admin'],
				['id' => 65, 'name' => 'list payments', 'guard_name' => 'admin'],
				['id' => 66, 'name' => 'view payments', 'guard_name' => 'admin'],
				['id' => 67, 'name' => 'add payments', 'guard_name' => 'admin'],
				['id' => 68, 'name' => 'edit payments', 'guard_name' => 'admin'],
				['id' => 69, 'name' => 'delete payments', 'guard_name' => 'admin'],
				['id' => 70, 'name' => 'restore payments', 'guard_name' => 'admin'],
				['id' => 71, 'name' => 'erease payments', 'guard_name' => 'admin'],
				['id' => 72, 'name' => 'list reviews', 'guard_name' => 'admin'],
				['id' => 73, 'name' => 'view reviews', 'guard_name' => 'admin'],
				['id' => 74, 'name' => 'add reviews', 'guard_name' => 'admin'],
				['id' => 75, 'name' => 'edit reviews', 'guard_name' => 'admin'],
				['id' => 76, 'name' => 'delete reviews', 'guard_name' => 'admin'],
				['id' => 77, 'name' => 'restore reviews', 'guard_name' => 'admin'],
				['id' => 78, 'name' => 'erease reviews', 'guard_name' => 'admin'],
				['id' => 79, 'name' => 'list addresses', 'guard_name' => 'admin'],
				['id' => 80, 'name' => 'view addresses', 'guard_name' => 'admin'],
				['id' => 81, 'name' => 'add addresses', 'guard_name' => 'admin'],
				['id' => 82, 'name' => 'edit addresses', 'guard_name' => 'admin'],
				['id' => 83, 'name' => 'delete addresses', 'guard_name' => 'admin'],
				['id' => 84, 'name' => 'restore addresses', 'guard_name' => 'admin'],
				['id' => 85, 'name' => 'erease addresses', 'guard_name' => 'admin']
			]);

        DB::table('role_has_permissions')->insert([
				['permission_id' => 1, 'role_id' => 1],
				['permission_id' => 2, 'role_id' => 1],
				['permission_id' => 3, 'role_id' => 1],
				['permission_id' => 4, 'role_id' => 1],
				['permission_id' => 5, 'role_id' => 1],
				['permission_id' => 6, 'role_id' => 1],
				['permission_id' => 7, 'role_id' => 1],
				['permission_id' => 8, 'role_id' => 1],
				['permission_id' => 9, 'role_id' => 1],
				['permission_id' => 10, 'role_id' => 1],
				['permission_id' => 11, 'role_id' => 1],
				['permission_id' => 12, 'role_id' => 1],
				['permission_id' => 13, 'role_id' => 1],
				['permission_id' => 14, 'role_id' => 1],
				['permission_id' => 15, 'role_id' => 1],
				['permission_id' => 16, 'role_id' => 1],
				['permission_id' => 17, 'role_id' => 1],
				['permission_id' => 18, 'role_id' => 1],
				['permission_id' => 19, 'role_id' => 1],
				['permission_id' => 20, 'role_id' => 1],
				['permission_id' => 21, 'role_id' => 1],
				['permission_id' => 22, 'role_id' => 1],
				['permission_id' => 23, 'role_id' => 1],
				['permission_id' => 24, 'role_id' => 1],
				['permission_id' => 25, 'role_id' => 1],
				['permission_id' => 26, 'role_id' => 1],
				['permission_id' => 27, 'role_id' => 1],
				['permission_id' => 28, 'role_id' => 1],
				['permission_id' => 29, 'role_id' => 1],
				['permission_id' => 30, 'role_id' => 1],
				['permission_id' => 31, 'role_id' => 1],
				['permission_id' => 32, 'role_id' => 1],
				['permission_id' => 33, 'role_id' => 1],
				['permission_id' => 34, 'role_id' => 1],
				['permission_id' => 35, 'role_id' => 1],
				['permission_id' => 36, 'role_id' => 1],
				['permission_id' => 37, 'role_id' => 1],
				['permission_id' => 38, 'role_id' => 1],
				['permission_id' => 39, 'role_id' => 1],
				['permission_id' => 40, 'role_id' => 1],
				['permission_id' => 41, 'role_id' => 1],
				['permission_id' => 42, 'role_id' => 1],
				['permission_id' => 43, 'role_id' => 1],
				['permission_id' => 44, 'role_id' => 1],
				['permission_id' => 45, 'role_id' => 1],
				['permission_id' => 46, 'role_id' => 1],
				['permission_id' => 47, 'role_id' => 1],
				['permission_id' => 48, 'role_id' => 1],
				['permission_id' => 49, 'role_id' => 1],
				['permission_id' => 50, 'role_id' => 1],
				['permission_id' => 51, 'role_id' => 1],
				['permission_id' => 52, 'role_id' => 1],
				['permission_id' => 53, 'role_id' => 1],
				['permission_id' => 54, 'role_id' => 1],
				['permission_id' => 55, 'role_id' => 1],
				['permission_id' => 56, 'role_id' => 1],
				['permission_id' => 57, 'role_id' => 1],
				['permission_id' => 58, 'role_id' => 1],
				['permission_id' => 59, 'role_id' => 1],
				['permission_id' => 60, 'role_id' => 1],
				['permission_id' => 61, 'role_id' => 1],
				['permission_id' => 62, 'role_id' => 1],
				['permission_id' => 63, 'role_id' => 1],
				['permission_id' => 64, 'role_id' => 1],
				['permission_id' => 65, 'role_id' => 1],
				['permission_id' => 66, 'role_id' => 1],
				['permission_id' => 67, 'role_id' => 1],
				['permission_id' => 68, 'role_id' => 1],
				['permission_id' => 69, 'role_id' => 1],
				['permission_id' => 70, 'role_id' => 1],
				['permission_id' => 71, 'role_id' => 1],
				['permission_id' => 72, 'role_id' => 1],
				['permission_id' => 73, 'role_id' => 1],
				['permission_id' => 74, 'role_id' => 1],
				['permission_id' => 75, 'role_id' => 1],
				['permission_id' => 76, 'role_id' => 1],
				['permission_id' => 77, 'role_id' => 1],
				['permission_id' => 78, 'role_id' => 1],
				['permission_id' => 79, 'role_id' => 1],
				['permission_id' => 80, 'role_id' => 1],
				['permission_id' => 81, 'role_id' => 1],
				['permission_id' => 82, 'role_id' => 1],
				['permission_id' => 83, 'role_id' => 1],
				['permission_id' => 84, 'role_id' => 1],
				['permission_id' => 85, 'role_id' => 1],
				['permission_id' => 1, 'role_id' => 2],
				['permission_id' => 2, 'role_id' => 2],
				['permission_id' => 4, 'role_id' => 2],
				['permission_id' => 5, 'role_id' => 2],
				['permission_id' => 6, 'role_id' => 2],
				['permission_id' => 8, 'role_id' => 2],
				['permission_id' => 9, 'role_id' => 2],
				['permission_id' => 11, 'role_id' => 2],
				['permission_id' => 12, 'role_id' => 2],
				['permission_id' => 13, 'role_id' => 2],
				['permission_id' => 15, 'role_id' => 2],
				['permission_id' => 16, 'role_id' => 2],
				['permission_id' => 18, 'role_id' => 2],
				['permission_id' => 19, 'role_id' => 2],
				['permission_id' => 20, 'role_id' => 2],
				['permission_id' => 22, 'role_id' => 2],
				['permission_id' => 23, 'role_id' => 2],
				['permission_id' => 25, 'role_id' => 2],
				['permission_id' => 26, 'role_id' => 2],
				['permission_id' => 27, 'role_id' => 2],
				['permission_id' => 29, 'role_id' => 2],
				['permission_id' => 30, 'role_id' => 2],
				['permission_id' => 32, 'role_id' => 2],
				['permission_id' => 33, 'role_id' => 2],
				['permission_id' => 34, 'role_id' => 2],
				['permission_id' => 36, 'role_id' => 2],
				['permission_id' => 37, 'role_id' => 2],
				['permission_id' => 39, 'role_id' => 2],
				['permission_id' => 40, 'role_id' => 2],
				['permission_id' => 41, 'role_id' => 2],
				['permission_id' => 43, 'role_id' => 2],
				['permission_id' => 44, 'role_id' => 2],
				['permission_id' => 46, 'role_id' => 2],
				['permission_id' => 47, 'role_id' => 2],
				['permission_id' => 48, 'role_id' => 2],
				['permission_id' => 49, 'role_id' => 2],
				['permission_id' => 51, 'role_id' => 2],
				['permission_id' => 52, 'role_id' => 2],
				['permission_id' => 53, 'role_id' => 2],
				['permission_id' => 54, 'role_id' => 2],
				['permission_id' => 56, 'role_id' => 2],
				['permission_id' => 57, 'role_id' => 2],
				['permission_id' => 58, 'role_id' => 2],
				['permission_id' => 60, 'role_id' => 2],
				['permission_id' => 61, 'role_id' => 2],
				['permission_id' => 63, 'role_id' => 2],
				['permission_id' => 64, 'role_id' => 2],
				['permission_id' => 65, 'role_id' => 2],
				['permission_id' => 66, 'role_id' => 2],
				['permission_id' => 68, 'role_id' => 2],
				['permission_id' => 69, 'role_id' => 2],
				['permission_id' => 70, 'role_id' => 2],
				['permission_id' => 72, 'role_id' => 2],
				['permission_id' => 73, 'role_id' => 2],
				['permission_id' => 75, 'role_id' => 2],
				['permission_id' => 76, 'role_id' => 2],
				['permission_id' => 77, 'role_id' => 2],
				['permission_id' => 79, 'role_id' => 2],
				['permission_id' => 80, 'role_id' => 2],
				['permission_id' => 82, 'role_id' => 2],
				['permission_id' => 83, 'role_id' => 2],
				['permission_id' => 84, 'role_id' => 2],
				['permission_id' => 1, 'role_id' => 3],
				['permission_id' => 2, 'role_id' => 3],
				['permission_id' => 4, 'role_id' => 3],
				['permission_id' => 8, 'role_id' => 3],
				['permission_id' => 9, 'role_id' => 3],
				['permission_id' => 11, 'role_id' => 3],
				['permission_id' => 15, 'role_id' => 3],
				['permission_id' => 16, 'role_id' => 3],
				['permission_id' => 18, 'role_id' => 3],
				['permission_id' => 22, 'role_id' => 3],
				['permission_id' => 23, 'role_id' => 3],
				['permission_id' => 25, 'role_id' => 3],
				['permission_id' => 29, 'role_id' => 3],
				['permission_id' => 30, 'role_id' => 3],
				['permission_id' => 32, 'role_id' => 3],
				['permission_id' => 36, 'role_id' => 3],
				['permission_id' => 37, 'role_id' => 3],
				['permission_id' => 39, 'role_id' => 3],
				['permission_id' => 43, 'role_id' => 3],
				['permission_id' => 44, 'role_id' => 3],
				['permission_id' => 46, 'role_id' => 3],
				['permission_id' => 48, 'role_id' => 3],
				['permission_id' => 49, 'role_id' => 3],
				['permission_id' => 51, 'role_id' => 3],
				['permission_id' => 53, 'role_id' => 3],
				['permission_id' => 54, 'role_id' => 3],
				['permission_id' => 56, 'role_id' => 3],
				['permission_id' => 60, 'role_id' => 3],
				['permission_id' => 61, 'role_id' => 3],
				['permission_id' => 63, 'role_id' => 3],
				['permission_id' => 65, 'role_id' => 3],
				['permission_id' => 66, 'role_id' => 3],
				['permission_id' => 68, 'role_id' => 3],
				['permission_id' => 72, 'role_id' => 3],
				['permission_id' => 73, 'role_id' => 3],
				['permission_id' => 75, 'role_id' => 3],
				['permission_id' => 79, 'role_id' => 3],
				['permission_id' => 80, 'role_id' => 3],
				['permission_id' => 82, 'role_id' => 3],
				['permission_id' => 1, 'role_id' => 4],
				['permission_id' => 2, 'role_id' => 4],
				['permission_id' => 8, 'role_id' => 4],
				['permission_id' => 9, 'role_id' => 4],
				['permission_id' => 15, 'role_id' => 4],
				['permission_id' => 16, 'role_id' => 4],
				['permission_id' => 22, 'role_id' => 4],
				['permission_id' => 23, 'role_id' => 4],
				['permission_id' => 29, 'role_id' => 4],
				['permission_id' => 30, 'role_id' => 4],
				['permission_id' => 36, 'role_id' => 4],
				['permission_id' => 37, 'role_id' => 4],
				['permission_id' => 43, 'role_id' => 4],
				['permission_id' => 44, 'role_id' => 4],
				['permission_id' => 48, 'role_id' => 4],
				['permission_id' => 49, 'role_id' => 4],
				['permission_id' => 53, 'role_id' => 4],
				['permission_id' => 54, 'role_id' => 4],
				['permission_id' => 60, 'role_id' => 4],
				['permission_id' => 61, 'role_id' => 4],
				['permission_id' => 65, 'role_id' => 4],
				['permission_id' => 66, 'role_id' => 4],
				['permission_id' => 72, 'role_id' => 4],
				['permission_id' => 73, 'role_id' => 4],
				['permission_id' => 79, 'role_id' => 4],
				['permission_id' => 80, 'role_id' => 4]
			]);
    }
}
